version: '3'
services:
  server:
    build: ./server 
    volumes:
      - ./server:/usr/src/app
    ports:
      - "5000:5000"

  client:
    build: ./client 
    volumes:
      - ./client:/usr/src/app
    ports:
      - "3000:3000"